title = About: ${Application.title} ${Application.version} 

closeAboutBox.Action.text = &Close

appDescLabel.text=<html>Un exemple d'export des cours et d'import des enseignants et des \u00E9tudiants vers HYPERPLANNING.

versionLabel.text=Version:

homepageLabel.text=Site web :

#NOI18N
imageLabel.icon=about.png
versionLabel.AccessibleContext.accessibleName=Product Version:
closeButton.text=Fermer
