# Application global resources

Application.name = Java_ExempleSvcWHP_Application
Application.title = Exemple d'utilisation du service web en java
Application.version = 1.3
Application.vendor = Index Education
Application.homepage = http://www.index-education.com
Application.description = A simple Java desktop application based on Swing Application Framework.
Application.vendorId = Sun
Application.id = ${Application.name}
Application.lookAndFeel = system
