fileMenu.text = Fichier
helpMenu.text = ?

# @Action resources

showAboutBox.Action.text = &About...
showAboutBox.Action.shortDescription = Show the application's information dialog

# status bar resources

StatusBar.messageTimeout = 5000
StatusBar.busyAnimationRate = 30
StatusBar.idleIcon = busyicons/idle-icon.png
StatusBar.busyIcons[0]  = busyicons/busy-icon0.png
StatusBar.busyIcons[1]  = busyicons/busy-icon1.png
StatusBar.busyIcons[2]  = busyicons/busy-icon2.png
StatusBar.busyIcons[3]  = busyicons/busy-icon3.png
StatusBar.busyIcons[4]  = busyicons/busy-icon4.png
StatusBar.busyIcons[5]  = busyicons/busy-icon5.png
StatusBar.busyIcons[6]  = busyicons/busy-icon6.png
StatusBar.busyIcons[7]  = busyicons/busy-icon7.png
StatusBar.busyIcons[8]  = busyicons/busy-icon8.png
StatusBar.busyIcons[9]  = busyicons/busy-icon9.png
StatusBar.busyIcons[10] = busyicons/busy-icon10.png
StatusBar.busyIcons[11] = busyicons/busy-icon11.png
StatusBar.busyIcons[12] = busyicons/busy-icon12.png
StatusBar.busyIcons[13] = busyicons/busy-icon13.png
StatusBar.busyIcons[14] = busyicons/busy-icon14.png
ExportCoursDates.Action.text=
ExportCoursDates.Action.accelerator=shift pressed C
ExportCoursDates.Action.shortDescription=
labelMotDePasse.text=Mot de passe
TfIdent.text=SW
tfPassword.text=SwSw
LabelSvcW.text=-
#NOI18N
LabelSvcW.background=255, 255, 255
jLabelAddrIp.text=Adresse IP
jLabelAddrPort.text=Port d'\u00e9coute
jTFAddrIP.text=127.0.0.1
jTFAddrPort.text=80
jTFSeparateur.text=;
aboutMenuItem.text=A propos...
exitMenuItem.text=Quitter
exitMenuItem.toolTipText=Quitter l'application
aboutMenuItem.toolTipText=
jMenuItemEffacer.text=Effacer la zone de message
jLabelIdent.text=Identifiant
jLabelDateDebut.text=Date de d\u00e9but
jLabelDateFin.text=Date de fin
jLabelFichierExportCours.text=Fichier de l'export
jLabelCheminExportCours.text=C:/Hyperplanning_export_Cours.txt
#NOI18N
jLabelCheminExportCours.foreground=0, 0, 255
jLabelSeparateur.text=S\u00e9parateur
jButtonExporterCours.text=Exporter
jButtonImporterEnseignant.text=Importer
jButtonImporterEtudiant.text=Importer
jButtonModifierCheminCours.toolTipText=Choisir le fichier d'export...
jButtonModifierCheminCours.text=...
jButtonModifierCheminEnseignant.toolTipText=Choisir le fichier d'import...
jButtonModifierCheminEnseignant.text=...
jButtonModifierCheminEtudiant.toolTipText=Choisir le fichier d'import...
jButtonModifierCheminEtudiant.text=...
jDateChooserDebut.dateFormatString=dd/MM/yyyy
jDateChooserFin.dateFormatString=dd/MM/yyyy
jLabelFichierImportEnseignant.text=Fichier d'import
jLabelFichierImportEtudiant.text=Fichier d'import
jPanelExportCours.TabConstraints.tabTitle=Export des cours
jPanelImportEnseignant.TabConstraints.tabTitle=Import des enseignants
jPanelImportEtudiant.TabConstraints.tabTitle=Import des \u00e9tudiants
jLabelCheminImportEnseignant.text=./MiseAJourEnseignant.txt
#NOI18N
jLabelCheminImportEnseignant.foreground=0, 0, 255
jLabelCheminImportEtudiant.text=./MiseAJourEtudiant.txt
#NOI18N
jLabelCheminImportEtudiant.foreground=0, 0, 255
jMenuItemExportCours.text=Export des cours
jMenuItemImportEnseignant.text=Import des enseignants
jMenuItemImportEtudiant.text=Import des \u00e9tudiants
jLabelRacine.text=Racine
jTFRacine.text=hpsw
